const Router = require('express').Router()
const AuthRouter = require('./AuthRouter')
const UserRouter = require('./UserRouter')
const BookRouter = require('./BookRouter')
const ReviewRouter = require('./ReviewRouter')
Router.use('/auth', AuthRouter)
Router.use('/user', UserRouter)
Router.use('/book', BookRouter)
Router.use('/review', ReviewRouter)
module.exports = Router
