const Router = require('express').Router()
const controller = require('../controllers/BookController')
const middleware = require('../middleware')
Router.post('', controller.createBook)
Router.get('/:bookId', controller.getBookById)
Router.get('/title/bookTitle', controller.getBookByTitle)
Router.get('/bookAuthor', controller.getBookByAuthor)
Router.post('/userbook/:userId/:bookId', controller.createUserBook)
Router.put('/userbook/:userbookId', controller.updateUserBook)
Router.get('/userbook/book/:userId/:bookId', controller.getUserBookByBookId)
Router.get('/allUserBooks/:userId', controller.getAllUserBooks)
Router.get('/userbook/:userId', controller.getAllUserBooksLibraries)
Router.get('/exist/:userId/:bookId', controller.getUserBookIfExist)
Router.get('/library/:userId/:library', controller.getAllUserBooksByLibrary)
Router.delete('/userbook/:bookId', controller.deleteUserBook)

module.exports = Router
